program gen_dual_demo
    ! Demonstrates fortsym_kernel_typed: operator-overloaded typed kernel
    ! emission for an arbitrary numeric derived type. See
    ! doc/kernel-typed-emission.md.
    !
    ! Unlike gen_demo, this generator does not write into src/generated/: the
    ! emitted subroutine references a caller-chosen type (here "dual_t") that
    ! is not part of fortsym itself, so committing it into the library tree
    ! would give the library a dependency on a demonstration-only numeric
    ! type. test/codegen/test_fortsym_kernel_typed.f90 is where the emitted
    ! text is actually compiled and run, against a real dual_t.
    use, intrinsic :: iso_fortran_env, only: output_unit, int64
    use fortsym_string, only: str_t, str, chars
    use fortsym_arena, only: arena_t
    use fortsym_expr, only: expr_t, sym, sin, sqrt, rat, &
        operator(+), operator(*), operator(/), operator(**)
    use fortsym_kernel_typed, only: typed_kernel_spec_t, emit_typed_kernel
    implicit none

    type(arena_t), target :: arena
    type(expr_t) :: x, y, f
    type(typed_kernel_spec_t) :: spec
    type(str_t) :: source
    logical :: ok
    character(:), allocatable :: message

    call arena%init()
    x = sym(arena, "x")
    y = sym(arena, "y")

    ! sin**2 exercises an integer power, sqrt a half-integer one, and 0.5*x a
    ! literal that the constructor policy below wraps in dual_t(...).
    f = sin(x*y)**2 + sqrt(x)/y + rat(arena, 1_int64, 2_int64)*x

    spec%name = str("dual_demo_f")
    allocate (spec%args(2), spec%outputs(1))
    spec%args(1) = str("x")
    spec%args(2) = str("y")
    spec%outputs(1) = str("f")
    spec%type_name = str("dual_t")
    spec%literal_constructor = str("dual_t")

    source = emit_typed_kernel([f], spec, ok, message)
    if (.not. ok) then
        write (output_unit, "(a)") "gen_dual_demo: emission failed: "//message
        error stop 1
    end if

    write (output_unit, "(a)") "! generated by app/gen_dual_demo.f90"
    write (output_unit, "(a)") "! f(x, y) = sin(x*y)**2 + sqrt(x)/y + 0.5*x"
    write (output_unit, "(a)") "! against a caller-supplied dual_t (forward-mode"
    write (output_unit, "(a)") "! automatic differentiation); see"
    write (output_unit, "(a)") "! test/codegen/test_fortsym_kernel_typed.f90 for a"
    write (output_unit, "(a)") "! compiled, checked run of exactly this kernel."
    write (output_unit, "(a)") chars(source)

end program gen_dual_demo
