program gen_emitted_kernel_audit
    use fortsym_arena, only: arena_t
    use fortsym_expr, only: expr_t, sym, operator(+), operator(-), &
        operator(*), operator(/), operator(**)
    use fortsym_products, only: jvp, vjp
    use fortsym_kernel, only: kernel_spec_t, emit_kernel
    use fortsym_rigorous_emit, only: rigorous_kernel_spec_t, interval_runtime, &
        emit_rigorous_kernel, emit_float_kernel
    use fortsym_string, only: str_t, str, chars
    implicit none

    type(arena_t), target :: arena
    type(expr_t) :: variables(2), direction(2), weights(2), values(2), products(2)
    type(kernel_spec_t) :: spec
    type(rigorous_kernel_spec_t) :: enclosure_spec
    type(str_t) :: source
    character(2048) :: output, revision
    character(:), allocatable :: message
    integer :: unit, status, length
    logical :: valid

    call get_command_argument(1, output, length=length, status=status)
    if (status /= 0 .or. length == 0) error stop "output path required"
    call get_command_argument(2, revision, length=length, status=status)
    if (status /= 0 .or. length == 0) error stop "source revision required"
    call arena%init()
    variables(1) = sym(arena, "x")
    variables(2) = sym(arena, "y")
    direction(1) = sym(arena, "dx")
    direction(2) = sym(arena, "dy")
    weights(1) = sym(arena, "b1")
    weights(2) = sym(arena, "b2")
    ! One definition drives all floating and enclosure leaves.
    values(1) = (variables(1) + variables(2))**2/(3 + variables(1)**2)
    values(2) = (variables(1) - variables(2))**3/5 + variables(2)**2
    open (newunit=unit, file=trim(output), status="replace", action="write", &
        iostat=status)
    if (status /= 0) error stop "cannot open generated audit module"
    write (unit, '(a)') "! Generated by gen_emitted_kernel_audit; do not edit."
    write (unit, '(a)') "! Source revision: "//trim(revision)
    write (unit, '(a)') "module emitted_audit_kernels"
    write (unit, '(a)') "implicit none"
    write (unit, '(a)') "character(*), parameter :: source_revision='"// &
        trim(revision)//"'"
    write (unit, '(a)') "contains"
    spec%generator = str("gen_emitted_kernel_audit")
    spec%generator_revision = str(trim(revision))
    spec%regenerate_command = str("cmake --build BUILD --target bench_emitted_kernels")
    spec%openmp_declare_target = .false.
    spec%openacc_routine_seq = .false.
    spec%pure_procedure = .true.
    allocate (spec%args(2), spec%outputs(2))
    spec%args(1) = str("x")
    spec%args(2) = str("y")
    spec%outputs(1) = str("r1")
    spec%outputs(2) = str("r2")
    spec%name = str("audit_primal")
    source = emit_kernel(values, spec, valid, message=message)
    call append_leaf()
    deallocate (spec%args)
    allocate (spec%args(4))
    spec%args(1) = str("x")
    spec%args(2) = str("y")
    spec%args(3) = str("dx")
    spec%args(4) = str("dy")
    spec%name = str("audit_jvp")
    products = jvp(values, variables, direction)
    source = emit_kernel(products, spec, valid, message=message)
    call append_leaf()
    spec%args(3) = str("b1")
    spec%args(4) = str("b2")
    spec%name = str("audit_vjp")
    products = vjp(values, variables, weights)
    source = emit_kernel(products, spec, valid, message=message)
    call append_leaf()
    enclosure_spec%generator = str("gen_emitted_kernel_audit")
    enclosure_spec%runtime = interval_runtime()
    allocate (enclosure_spec%args(2), enclosure_spec%outputs(2))
    enclosure_spec%args(1) = str("x")
    enclosure_spec%args(2) = str("y")
    enclosure_spec%outputs(1) = str("r1")
    enclosure_spec%outputs(2) = str("r2")
    enclosure_spec%name = str("audit_interval")
    source = emit_rigorous_kernel(values, enclosure_spec, valid, message)
    call append_leaf()
    enclosure_spec%name = str("audit_paired_float")
    source = emit_float_kernel(values, enclosure_spec, valid, message)
    call append_leaf()
    write (unit, '(a)') "end module emitted_audit_kernels"
    close (unit)

contains

    subroutine append_leaf()
        if (.not. valid) then
            print '(a)', message
            error stop "audit kernel emission refused"
        end if
        write (unit, '(a)') chars(source)
    end subroutine append_leaf
end program gen_emitted_kernel_audit
