program gen_taylor_demo
    ! Demonstrates fortsym_kernel_taylor: order-by-order Taylor-series (SSA)
    ! emission. See doc/kernel-taylor-emission.md.
    !
    ! As with gen_dual_demo, the emitted subroutine calls caller-named
    ! building blocks (ts_mul, ts_div, ts_sincos, ts_exp) that are not part
    ! of fortsym itself, so the output is printed here rather than committed
    ! into src/generated/. test/codegen/test_fortsym_kernel_taylor.f90
    ! compiles this exact emission against a hand-written truncated-power-
    ! series harness and checks the resulting coefficients.
    use, intrinsic :: iso_fortran_env, only: output_unit
    use fortsym_string, only: str_t, str, chars
    use fortsym_arena, only: arena_t
    use fortsym_expr, only: expr_t, sym, sin, exp, num, &
        operator(+), operator(-), operator(*), operator(/)
    use fortsym_kernel_taylor, only: taylor_emit_spec_t, emit_taylor_step
    implicit none

    type(arena_t), target :: arena
    type(expr_t) :: x, f1, f2, f3
    type(taylor_emit_spec_t) :: spec
    type(str_t) :: source
    logical :: ok
    character(:), allocatable :: message

    call arena%init()
    x = sym(arena, "x")

    ! sin(x) exercises ts_sincos, x/(1-x) exercises ts_mul and, through the
    ! reciprocal of (1-x), ts_div, and exp(x) exercises ts_exp -- the four
    ! call-based building blocks this module supplies, all sharing one
    ! order-k step subroutine and one input series.
    f1 = sin(x)
    f2 = x/(num(arena, 1) - x)
    f3 = exp(x)

    spec%name = str("taylor_demo_step")
    allocate (spec%args(1), spec%outputs(3))
    spec%args(1) = str("x")
    spec%outputs(1) = str("f1")
    spec%outputs(2) = str("f2")
    spec%outputs(3) = str("f3")
    spec%mul_name = str("ts_mul")
    spec%div_name = str("ts_div")
    spec%sincos_name = str("ts_sincos")
    spec%exp_name = str("ts_exp")

    source = emit_taylor_step([f1, f2, f3], spec, ok, message)
    if (.not. ok) then
        write (output_unit, "(a)") "gen_taylor_demo: emission failed: "//message
        error stop 1
    end if

    write (output_unit, "(a)") "! generated by app/gen_taylor_demo.f90"
    write (output_unit, "(a)") "! f1 = sin(x), f2 = x/(1-x), f3 = exp(x)"
    write (output_unit, "(a)") "! a downstream driver allocates every listed"
    write (output_unit, "(a)") "! series array, seeds x(0:1) = [0, 1], and calls"
    write (output_unit, "(a)") "! this subroutine for k = 0, 1, 2, ... in order;"
    write (output_unit, "(a)") "! see test/codegen/test_fortsym_kernel_taylor.f90"
    write (output_unit, "(a)") "! for exactly that driver, checked against"
    write (output_unit, "(a)") "! independent closed forms."
    write (output_unit, "(a)") chars(source)

end program gen_taylor_demo
