program test_fortsym_latex
    use fortsym_arena, only: arena_t
    use fortsym_dialect, only: DIA_LATEX, dialect
    use fortsym_expr
    use fortsym_diff, only: diff
    use fortsym_latex, only: latex_t
    use fortsym_parse, only: parse_expr_in
    implicit none

    type(arena_t), target :: arena
    type(expr_t) :: x, y, q0, weight, bcon, zeta, indexed, parsed
    type(expr_t) :: derivative, simple_partial, curl
    type(expr_t) :: curl_args(1)
    type(latex_t) :: tex, collision
    character(:), allocatable :: message
    logical :: ok
    integer :: failures, unit, ios, command_status

    failures = 0
    call arena%init()
    x = sym(arena, "x")
    y = sym(arena, "y")
    q0 = sym(arena, "q0")
    weight = sym(arena, "weight_1_bar")
    bcon = sym(arena, "Bcon_r")
    zeta = sym(arena, "zeta")
    indexed = sym(arena, "v(1,1)")
    curl_args(1) = x
    curl = func("curl_t", curl_args)
    derivative = partial(curl, num(arena, 2))
    simple_partial = partial(x, num(arena, 2))

    call tex%source("latex fixture")
    call tex%name("Bcon_r", "\mathcal{B}^{r}", ok, message)
    call check("register notation", ok, failures)
    call tex%eq("sum", x + y, ok=ok, message=message)
    call check("sum", ok, failures)
    call tex%eq("product", x*y, ok=ok, message=message)
    call check("product", ok, failures)
    call tex%eq("quotient", x/y, ok=ok, message=message)
    call check("quotient", ok, failures)
    call tex%eq("power", x**2, ok=ok, message=message)
    call check("power", ok, failures)
    call tex%eq("root", sqrt(x), ok=ok, message=message)
    call check("root", ok, failures)
    call tex%eq("logarithm", log(x), ok=ok, message=message)
    call check("logarithm", ok, failures)
    call tex%eq("q0", q0, ok=ok, message=message)
    call check("trailing digit", ok, failures)
    call tex%eq("weight", weight, ok=ok, message=message)
    call check("modifier", ok, failures)
    call tex%eq("registered", bcon**2, ok=ok, message=message)
    call check("registered scripted symbol", ok, failures)
    call tex%eq("negative", -x, ok=ok, message=message)
    call check("negative symbol", ok, failures)
    call tex%eq("negpower", (x + y)**(-1), ok=ok, message=message)
    call check("negative power", ok, failures)
    call tex%eq("greek", zeta, ok=ok, message=message)
    call check("Greek symbol", ok, failures)
    call tex%eq("indexed", indexed, ok=ok, message=message)
    call check("indexed symbol", ok, failures)
    call tex%eq("partial", derivative, ok=ok, message=message)
    call check("partial derivative", ok, failures)
    call tex%relation("relation", x, y, ok=ok, message=message)
    call check("relation", ok, failures)
    call check("partial derivative propagates", &
        diff(simple_partial, x) == partial(num(arena, 1), num(arena, 2)), failures)
    call tex%eq("conditioned", x, "r > 0", ok, message)
    call check("assumption registration", ok, failures)

    call tex%write("/tmp/fortsym-latex-test.tex", ok, message)
    call check("write", ok, failures)
    call tex%write("/tmp/fortsym-latex-test-second.tex", ok, message)
    call check("second write", ok, failures)
    call execute_command_line("cmp -s /tmp/fortsym-latex-test.tex "// &
        "/tmp/fortsym-latex-test-second.tex", exitstat=ios)
    call check("byte reproducibility", ios == 0, failures)
    open (newunit=unit, file="/tmp/fortsym-latex-test.tex", status="old", &
        action="read", iostat=ios)
    call check("open output", ios == 0, failures)
    if (ios == 0) then
        call check_line(unit, "% generated by fortsym -- do not edit", &
            "banner", failures)
        call check_line(unit, "% derivation: latex fixture", "source", failures)
        call check_line(unit, "\newcommand{\eqsum}{x + y}", "sum output", failures)
        call check_line(unit, "\newcommand{\eqproduct}{x\,y}", &
            "product output", failures)
        call check_line(unit, "\newcommand{\eqquotient}{\frac{x}{y}}", &
            "quotient output", failures)
        call check_line(unit, "\newcommand{\eqpower}{x^{2}}", &
            "power output", failures)
        call check_line(unit, "\newcommand{\eqroot}{\sqrt{x}}", &
            "root output", failures)
        call check_line(unit, "\newcommand{\eqlogarithm}{\ln{\left(x\right)}}", &
            "log output", failures)
        call check_line(unit, "\newcommand{\eqqZero}{q_{0}}", &
            "digit output", failures)
        call check_line(unit, "\newcommand{\eqweight}{\bar{\mathrm{weight}_{1}}}", &
            "modifier output", failures)
        call check_line(unit, "\newcommand{\eqregistered}{\left(\mathcal{B}^{r}\right)^{2}}", &
            "registered output", failures)
        call check_line(unit, "\newcommand{\eqnegative}{-x}", &
            "negative output", failures)
        call check_line(unit, "\newcommand{\eqnegpower}{\frac{1}{x + y}}", &
            "negative power output", failures)
        call check_line(unit, "\newcommand{\eqgreek}{\zeta}", &
            "Greek output", failures)
        call check_line(unit, "\newcommand{\eqindexed}{v_{1,1}}", &
            "indexed output", failures)
        call check_line(unit, "\newcommand{\eqpartial}{\partial_{2}\left("// &
            "\operatorname{curl}_{\mathrm{t}}\boldsymbol{x}\right)}", &
            "partial output", failures)
        call check_line(unit, "\newcommand{\eqrelation}{x = y}", &
            "relation output", failures)
        call check_line(unit, "\newcommand{\eqconditioned}{x}", &
            "conditioned output", failures)
        call check_line(unit, "\newcommand{\assumptioneqconditioned}{r > 0}", &
            "assumption output", failures)
        read (unit, "(a)", iostat=ios)
        call check("no extra output", ios < 0, failures)
        close (unit)
    end if

    call collision%eq("a/b", x, ok=ok, message=message)
    call check("first collision label", ok, failures)
    call collision%eq("aXb", y, ok=ok, message=message)
    call check("macro collision is refused", .not. ok .and. &
        index(message, "aXb") > 0 .and. index(message, "a/b") > 0, failures)

    parsed = parse_expr_in(arena, "x", dialect(DIA_LATEX), ok, message)
    call check("LaTeX parser is refused", .not. ok .and. &
        index(message, "write-only") > 0, failures)

    call execute_command_line("command -v pdflatex >/dev/null 2>&1", &
        exitstat=ios, cmdstat=command_status)
    if (command_status == 0 .and. ios == 0) then
        call write_document()
        call execute_command_line("pdflatex -interaction=nonstopmode -halt-on-error "// &
            "-output-directory=/tmp /tmp/fortsym-latex-document.tex >/dev/null", &
            exitstat=ios)
        call check("pdflatex typesetting", ios == 0, failures)
    else
        print *, "SKIP pdflatex typesetting: executable unavailable"
    end if

    if (failures == 0) then
        print *, "test_fortsym_latex: all checks passed"
    else
        print *, "test_fortsym_latex: ", failures, " check(s) FAILED"
        error stop 1
    end if

contains

    subroutine check(label, condition, failures)
        character(*), intent(in) :: label
        logical, intent(in) :: condition
        integer, intent(inout) :: failures

        if (condition) return
        failures = failures + 1
        print *, "FAIL ", label
    end subroutine check

    subroutine check_line(unit, expected, label, failures)
        integer, intent(in) :: unit
        character(*), intent(in) :: expected, label
        integer, intent(inout) :: failures
        character(4096) :: line
        integer :: ios

        read (unit, "(a)", iostat=ios) line
        call check(label, ios == 0 .and. trim(line) == expected, failures)
        if (ios == 0 .and. trim(line) /= expected) then
            print *, "      got  [", trim(line), "]"
            print *, "      want [", expected, "]"
        end if
    end subroutine check_line

    subroutine write_document()
        integer :: document_unit, ios

        open (newunit=document_unit, file="/tmp/fortsym-latex-document.tex", &
            status="replace", action="write", iostat=ios)
        if (ios /= 0) then
            call check("open LaTeX document", .false., failures)
            return
        end if
        write (document_unit, "(a)") "\documentclass{article}"
        write (document_unit, "(a)") "\usepackage{amsmath}"
        write (document_unit, "(a)") "\input{/tmp/fortsym-latex-test.tex}"
        write (document_unit, "(a)") "\begin{document}"
        write (document_unit, "(a)") "$\eqsum, \eqquotient, \eqregistered.$"
        write (document_unit, "(a)") "\end{document}"
        close (document_unit)
    end subroutine write_document

end program test_fortsym_latex
