module fortsym_enzyme
    use fortsym_string, only: str_t, strbuf_t, chars
    implicit none
    private

    type, public :: enzyme_scalar_wrapper_spec_t
        type(str_t) :: module_name
        type(str_t) :: wrapper_prefix
        type(str_t) :: primal_symbol
        integer :: active_inputs = 1
        type(str_t) :: analytical_jvp_symbol
        type(str_t) :: custom_forward_symbol
        type(str_t) :: custom_forward_counter_symbol
        type(str_t) :: generator
        type(str_t) :: generator_revision
        type(str_t) :: regenerate_command
    end type enzyme_scalar_wrapper_spec_t

    type, public :: enzyme_scalar_vector_wrapper_spec_t
        type(str_t) :: module_name
        type(str_t) :: wrapper_prefix
        type(str_t) :: primal_symbol
        integer :: vector_size = 1
        type(str_t) :: generator
        type(str_t) :: generator_revision
        type(str_t) :: regenerate_command
    end type enzyme_scalar_vector_wrapper_spec_t

    type, public :: enzyme_fixed_array_wrapper_spec_t
        type(str_t) :: module_name
        type(str_t) :: wrapper_prefix
        type(str_t) :: primal_symbol
        integer, allocatable :: array_sizes(:)
        integer :: inactive_integer_count = 0
        type(str_t) :: generator
        type(str_t) :: generator_revision
        type(str_t) :: regenerate_command
    end type enzyme_fixed_array_wrapper_spec_t

    type, public :: enzyme_fixed_array_map_wrapper_spec_t
        type(str_t) :: module_name
        type(str_t) :: wrapper_prefix
        type(str_t) :: primal_symbol
        integer :: input_size = 1
        integer :: output_size = 1
        type(str_t) :: generator
        type(str_t) :: generator_revision
        type(str_t) :: regenerate_command
    end type enzyme_fixed_array_map_wrapper_spec_t

    public :: emit_enzyme_fixed_array_map_wrapper
    public :: emit_enzyme_fixed_array_wrapper
    public :: emit_enzyme_scalar_vector_wrapper
    public :: emit_enzyme_scalar_wrapper

contains

    function emit_enzyme_fixed_array_map_wrapper(spec) result(source)
        type(enzyme_fixed_array_map_wrapper_spec_t), intent(in) :: spec
        type(str_t) :: source
        type(strbuf_t) :: buffer
        character(:), allocatable :: module_name, prefix, primal

        call validate_fixed_array_map_spec(spec)
        module_name = chars(spec%module_name)
        prefix = chars(spec%wrapper_prefix)
        primal = chars(spec%primal_symbol)
        call append_line(buffer, "! Generated by fortsym. Do not edit.")
        call append_line(buffer, "! Generator: "//chars(spec%generator))
        if (len(chars(spec%generator_revision)) > 0) then
            call append_line(buffer, &
                "! Generator revision: "//chars(spec%generator_revision))
        end if
        call append_line(buffer, &
            "! Regenerate with: "//chars(spec%regenerate_command))
        call buffer%newline()
        call append_line(buffer, "module "//module_name)
        call append_line(buffer, &
            "    use, intrinsic :: iso_c_binding, only: c_double, c_funloc, c_funptr")
        call append_line(buffer, "    implicit none")
        call append_line(buffer, "    private")
        call buffer%newline()
        call append_line(buffer, "    public :: "//prefix//"_jvp")
        call buffer%newline()
        call append_line(buffer, "    interface")
        call append_line(buffer, &
            "        subroutine primal(x, y) bind(c, name="""//primal//""")")
        call append_line(buffer, "            import :: c_double")
        call append_line(buffer, "            real(c_double), intent(in) :: x(*)")
        call append_line(buffer, "            real(c_double), intent(out) :: y(*)")
        call append_line(buffer, "        end subroutine primal")
        call buffer%newline()
        call append_line(buffer, &
            "        subroutine enzyme_fwddiff(function_pointer, x, tangent, y, product) &")
        call append_line(buffer, &
            "                bind(c, name=""__enzyme_fwddiff"")")
        call append_line(buffer, "            import :: c_double, c_funptr")
        call append_line(buffer, &
            "            type(c_funptr), value :: function_pointer")
        call append_line(buffer, &
            "            real(c_double), intent(in) :: x(*), tangent(*)")
        call append_line(buffer, &
            "            real(c_double), intent(out) :: y(*), product(*)")
        call append_line(buffer, "        end subroutine enzyme_fwddiff")
        call append_line(buffer, "    end interface")
        call buffer%newline()
        call append_line(buffer, "contains")
        call buffer%newline()
        call append_line(buffer, &
            "    subroutine "//prefix//"_jvp(x, tangent, y, product)")
        call append_line(buffer, "        real(c_double), intent(in) :: x("// &
            integer_text(spec%input_size)//"), tangent("// &
            integer_text(spec%input_size)//")")
        call append_line(buffer, "        real(c_double), intent(out) :: y("// &
            integer_text(spec%output_size)//"), product("// &
            integer_text(spec%output_size)//")")
        call buffer%newline()
        call append_line(buffer, &
            "        call enzyme_fwddiff(c_funloc(primal), x, tangent, y, product)")
        call append_line(buffer, "    end subroutine "//prefix//"_jvp")
        call buffer%newline()
        call append_line(buffer, "end module "//module_name)
        source = buffer%to_str()
    end function emit_enzyme_fixed_array_map_wrapper

    subroutine validate_fixed_array_map_spec(spec)
        type(enzyme_fixed_array_map_wrapper_spec_t), intent(in) :: spec

        if (len(chars(spec%module_name)) == 0) then
            error stop "Enzyme fixed-array map module_name is required"
        end if
        if (len(chars(spec%wrapper_prefix)) == 0) then
            error stop "Enzyme fixed-array map wrapper_prefix is required"
        end if
        if (len(chars(spec%primal_symbol)) == 0) then
            error stop "Enzyme fixed-array map primal_symbol is required"
        end if
        if (spec%input_size < 1 .or. spec%output_size < 1) then
            error stop "Enzyme fixed-array map extents must be positive"
        end if
    end subroutine validate_fixed_array_map_spec

    function emit_enzyme_fixed_array_wrapper(spec) result(source)
        type(enzyme_fixed_array_wrapper_spec_t), intent(in) :: spec
        type(str_t) :: source
        type(strbuf_t) :: buffer
        character(:), allocatable :: module_name, prefix, primal
        integer :: i

        call validate_fixed_array_spec(spec)
        module_name = chars(spec%module_name)
        prefix = chars(spec%wrapper_prefix)
        primal = chars(spec%primal_symbol)
        call append_fixed_array_banner(buffer, spec)
        call append_line(buffer, "module "//module_name)
        call append_line(buffer, &
            "    use, intrinsic :: iso_c_binding, only: c_double, c_funloc, c_funptr, c_int")
        call append_line(buffer, "    implicit none")
        call append_line(buffer, "    private")
        call buffer%newline()
        call append_line(buffer, "    public :: "//prefix//"_jvp, "//prefix//"_vjp")
        call buffer%newline()
        call append_line(buffer, "    interface")
        call buffer%append("        function primal(")
        call append_array_names(buffer, size(spec%array_sizes), .false.)
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(") result(value) bind(c, name="""//primal//""")")
        call buffer%newline()
        call append_line(buffer, "            import :: c_double, c_int")
        call append_line(buffer, "            real(c_double) :: value")
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "            real(c_double), intent(in) :: x"//integer_text(i)//"(*)")
        end do
        call append_inactive_integer_declarations(buffer, &
            spec%inactive_integer_count, 12)
        call append_line(buffer, "        end function primal")
        call buffer%newline()
        call buffer%append("        function enzyme_fwddiff(function_pointer, ")
        call append_array_names(buffer, size(spec%array_sizes), .true.)
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(") result(derivative) bind(c, name=""__enzyme_fwddiff"")")
        call buffer%newline()
        call append_line(buffer, "            import :: c_double, c_funptr, c_int")
        call append_line(buffer, "            type(c_funptr), value :: function_pointer")
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "            real(c_double), intent(in) :: x"//integer_text(i)// &
                "(*), tangent"//integer_text(i)//"(*)")
        end do
        call append_inactive_integer_declarations(buffer, &
            spec%inactive_integer_count, 12)
        call append_line(buffer, "            real(c_double) :: derivative")
        call append_line(buffer, "        end function enzyme_fwddiff")
        call buffer%newline()
        call buffer%append("        function enzyme_autodiff(function_pointer, ")
        call append_array_names(buffer, size(spec%array_sizes), .true., "bar")
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(") result(value) bind(c, name=""__enzyme_autodiff"")")
        call buffer%newline()
        call append_line(buffer, "            import :: c_double, c_funptr, c_int")
        call append_line(buffer, "            type(c_funptr), value :: function_pointer")
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "            real(c_double), intent(in) :: x"//integer_text(i)//"(*)")
            call append_line(buffer, &
                "            real(c_double), intent(inout) :: bar"//integer_text(i)//"(*)")
        end do
        call append_inactive_integer_declarations(buffer, &
            spec%inactive_integer_count, 12)
        call append_line(buffer, "            real(c_double) :: value")
        call append_line(buffer, "        end function enzyme_autodiff")
        call append_line(buffer, "    end interface")
        call buffer%newline()
        call append_line(buffer, "contains")
        call buffer%newline()
        call buffer%append("    function "//prefix//"_jvp(")
        call append_array_names(buffer, size(spec%array_sizes), .true.)
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(") result(derivative)")
        call buffer%newline()
        call append_fixed_array_declarations(buffer, spec, .true.)
        call append_line(buffer, "        real(c_double) :: derivative")
        call buffer%newline()
        call buffer%append("        derivative = enzyme_fwddiff(c_funloc(primal), ")
        call append_array_names(buffer, size(spec%array_sizes), .true.)
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(")")
        call buffer%newline()
        call append_line(buffer, "    end function "//prefix//"_jvp")
        call buffer%newline()
        call buffer%append("    function "//prefix//"_vjp(")
        call append_array_names(buffer, size(spec%array_sizes), .false.)
        call buffer%append(", cotangent, ")
        call append_bar_names(buffer, size(spec%array_sizes))
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(") result(value)")
        call buffer%newline()
        call append_fixed_array_declarations(buffer, spec, .false.)
        call append_line(buffer, "        real(c_double), intent(in) :: cotangent")
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "        real(c_double), intent(out) :: bar"//integer_text(i)// &
                "("//integer_text(spec%array_sizes(i))//")")
        end do
        call append_line(buffer, "        real(c_double) :: value")
        call buffer%newline()
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, "        bar"//integer_text(i)//" = 0.0_c_double")
        end do
        call buffer%append("        value = enzyme_autodiff(c_funloc(primal), ")
        call append_array_names(buffer, size(spec%array_sizes), .true., "bar")
        call append_inactive_integer_names(buffer, spec%inactive_integer_count)
        call buffer%append(")")
        call buffer%newline()
        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "        bar"//integer_text(i)//" = cotangent*bar"//integer_text(i))
        end do
        call append_line(buffer, "    end function "//prefix//"_vjp")
        call buffer%newline()
        call append_line(buffer, "end module "//module_name)
        source = buffer%to_str()
    end function emit_enzyme_fixed_array_wrapper

    subroutine validate_fixed_array_spec(spec)
        type(enzyme_fixed_array_wrapper_spec_t), intent(in) :: spec

        if (len(chars(spec%module_name)) == 0) then
            error stop "Enzyme fixed-array wrapper module_name is required"
        end if
        if (len(chars(spec%wrapper_prefix)) == 0) then
            error stop "Enzyme fixed-array wrapper wrapper_prefix is required"
        end if
        if (len(chars(spec%primal_symbol)) == 0) then
            error stop "Enzyme fixed-array wrapper primal_symbol is required"
        end if
        if (.not. allocated(spec%array_sizes)) then
            error stop "Enzyme fixed-array wrapper array_sizes is required"
        end if
        if (size(spec%array_sizes) < 1 .or. size(spec%array_sizes) > 4) then
            error stop "Enzyme fixed-array wrappers support one to four arrays"
        end if
        if (any(spec%array_sizes < 1)) then
            error stop "Enzyme fixed-array wrapper extents must be positive"
        end if
        if (spec%inactive_integer_count < 0 .or. &
            spec%inactive_integer_count > 4) then
            error stop "Enzyme fixed-array wrappers support zero to four inactive integers"
        end if
    end subroutine validate_fixed_array_spec

    subroutine append_fixed_array_banner(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_fixed_array_wrapper_spec_t), intent(in) :: spec

        call append_line(buffer, "! Generated by fortsym. Do not edit.")
        call append_line(buffer, "! Generator: "//chars(spec%generator))
        if (len(chars(spec%generator_revision)) > 0) then
            call append_line(buffer, &
                "! Generator revision: "//chars(spec%generator_revision))
        end if
        call append_line(buffer, &
            "! Regenerate with: "//chars(spec%regenerate_command))
        call buffer%newline()
    end subroutine append_fixed_array_banner

    subroutine append_fixed_array_declarations(buffer, spec, tangent)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_fixed_array_wrapper_spec_t), intent(in) :: spec
        logical, intent(in) :: tangent
        integer :: i

        do i = 1, size(spec%array_sizes)
            call append_line(buffer, &
                "        real(c_double), intent(in) :: x"//integer_text(i)// &
                "("//integer_text(spec%array_sizes(i))//")")
            if (tangent) then
                call append_line(buffer, &
                    "        real(c_double), intent(in) :: tangent"// &
                    integer_text(i)//"("//integer_text(spec%array_sizes(i))//")")
            end if
        end do
        call append_inactive_integer_declarations(buffer, &
            spec%inactive_integer_count, 8)
    end subroutine append_fixed_array_declarations

    subroutine append_inactive_integer_names(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: i

        do i = 1, count
            call buffer%append(", selector"//integer_text(i))
        end do
    end subroutine append_inactive_integer_names

    subroutine append_inactive_integer_declarations(buffer, count, indentation)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count, indentation
        character(:), allocatable :: spaces
        integer :: i

        spaces = repeat(" ", indentation)
        do i = 1, count
            call append_line(buffer, spaces//"integer(c_int), value :: selector"// &
                integer_text(i))
        end do
    end subroutine append_inactive_integer_declarations

    subroutine append_array_names(buffer, count, paired, shadow_prefix)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        logical, intent(in) :: paired
        character(*), intent(in), optional :: shadow_prefix
        character(:), allocatable :: shadow
        integer :: i

        shadow = "tangent"
        if (present(shadow_prefix)) shadow = shadow_prefix
        do i = 1, count
            if (i > 1) call buffer%append(", ")
            call buffer%append("x"//integer_text(i))
            if (paired) call buffer%append(", "//shadow//integer_text(i))
        end do
    end subroutine append_array_names

    subroutine append_bar_names(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: i

        do i = 1, count
            if (i > 1) call buffer%append(", ")
            call buffer%append("bar"//integer_text(i))
        end do
    end subroutine append_bar_names

    function integer_text(value) result(text)
        integer, intent(in) :: value
        character(:), allocatable :: text
        character(32) :: buffer

        write (buffer, "(i0)") value
        text = trim(buffer)
    end function integer_text

    function emit_enzyme_scalar_vector_wrapper(spec) result(source)
        type(enzyme_scalar_vector_wrapper_spec_t), intent(in) :: spec
        type(str_t) :: source
        type(strbuf_t) :: buffer
        character(:), allocatable :: module_name, prefix, primal

        call validate_scalar_vector_spec(spec)
        module_name = chars(spec%module_name)
        prefix = chars(spec%wrapper_prefix)
        primal = chars(spec%primal_symbol)
        call append_scalar_vector_banner(buffer, spec)
        call append_line(buffer, "module "//module_name)
        call append_line(buffer, &
            "    use, intrinsic :: iso_c_binding, only: c_double, c_funloc, c_funptr")
        call append_line(buffer, "    implicit none")
        call append_line(buffer, "    private")
        call buffer%newline()
        call append_line(buffer, "    public :: "//prefix//"_jvp, "//prefix//"_vjp")
        call buffer%newline()
        call append_line(buffer, "    interface")
        call append_line(buffer, &
            "        function primal(x, values) result(value) bind(c, name="""// &
            primal//""")")
        call append_line(buffer, "            import :: c_double")
        call append_line(buffer, "            real(c_double) :: value")
        call append_line(buffer, "            real(c_double), intent(in) :: x, values(*)")
        call append_line(buffer, "        end function primal")
        call buffer%newline()
        call append_line(buffer, &
            "        function enzyme_fwddiff(function_pointer, x, tangent, values, dvalues) result(derivative) &")
        call append_line(buffer, &
            "                bind(c, name=""__enzyme_fwddiff"")")
        call append_line(buffer, "            import :: c_double, c_funptr")
        call append_line(buffer, &
            "            type(c_funptr), value :: function_pointer")
        call append_line(buffer, &
            "            real(c_double), intent(in) :: x, tangent, values(*), dvalues(*)")
        call append_line(buffer, "            real(c_double) :: derivative")
        call append_line(buffer, "        end function enzyme_fwddiff")
        call buffer%newline()
        call append_line(buffer, &
            "        function enzyme_autodiff(function_pointer, x, xbar, values, values_bar) result(value) &")
        call append_line(buffer, &
            "                bind(c, name=""__enzyme_autodiff"")")
        call append_line(buffer, "            import :: c_double, c_funptr")
        call append_line(buffer, &
            "            type(c_funptr), value :: function_pointer")
        call append_line(buffer, "            real(c_double), intent(in) :: x")
        call append_line(buffer, "            real(c_double), intent(inout) :: xbar")
        call append_line(buffer, "            real(c_double), intent(in) :: values(*)")
        call append_line(buffer, &
            "            real(c_double), intent(inout) :: values_bar(*)")
        call append_line(buffer, "            real(c_double) :: value")
        call append_line(buffer, "        end function enzyme_autodiff")
        call append_line(buffer, "    end interface")
        call buffer%newline()
        call append_line(buffer, "contains")
        call buffer%newline()
        call append_line(buffer, "    function "//prefix// &
            "_jvp(x, values, tangent, dvalues) result(derivative)")
        call append_line(buffer, &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call append_scalar_vector_declarations(buffer, spec%vector_size, .true.)
        call append_line(buffer, "        real(c_double) :: derivative")
        call buffer%newline()
        call append_line(buffer, &
            "        derivative = enzyme_fwddiff(c_funloc(primal), x, tangent, values, dvalues)")
        call append_line(buffer, "    end function "//prefix//"_jvp")
        call buffer%newline()
        call append_line(buffer, "    subroutine "//prefix// &
            "_vjp(x, values, cotangent, xbar, values_bar)")
        call append_line(buffer, &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call append_scalar_vector_declarations(buffer, spec%vector_size, .false.)
        call append_line(buffer, "        real(c_double), intent(in) :: cotangent")
        call append_line(buffer, "        real(c_double), intent(out) :: xbar")
        call buffer%append("        real(c_double), intent(out) :: values_bar(")
        call append_integer(buffer, spec%vector_size)
        call buffer%append(")")
        call buffer%newline()
        call append_line(buffer, "        real(c_double) :: ignored_value")
        call buffer%newline()
        call append_line(buffer, "        xbar = 0.0_c_double")
        call append_line(buffer, "        values_bar = 0.0_c_double")
        call append_line(buffer, &
            "        ignored_value = enzyme_autodiff(c_funloc(primal), x, xbar, values, values_bar)")
        call append_line(buffer, "        xbar = cotangent*xbar")
        call append_line(buffer, "        values_bar = cotangent*values_bar")
        call append_line(buffer, "    end subroutine "//prefix//"_vjp")
        call buffer%newline()
        call append_line(buffer, "end module "//module_name)
        source = buffer%to_str()
    end function emit_enzyme_scalar_vector_wrapper

    subroutine validate_scalar_vector_spec(spec)
        type(enzyme_scalar_vector_wrapper_spec_t), intent(in) :: spec

        if (len(chars(spec%module_name)) == 0) then
            error stop "Enzyme scalar-vector wrapper module_name is required"
        end if
        if (len(chars(spec%wrapper_prefix)) == 0) then
            error stop "Enzyme scalar-vector wrapper_prefix is required"
        end if
        if (len(chars(spec%primal_symbol)) == 0) then
            error stop "Enzyme scalar-vector wrapper primal_symbol is required"
        end if
        if (spec%vector_size < 1) then
            error stop "Enzyme scalar-vector wrapper vector_size must be positive"
        end if
    end subroutine validate_scalar_vector_spec

    subroutine append_scalar_vector_banner(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_vector_wrapper_spec_t), intent(in) :: spec

        call append_line(buffer, "! Generated by fortsym. Do not edit.")
        call append_line(buffer, "! Generator: "//chars(spec%generator))
        if (len(chars(spec%generator_revision)) > 0) then
            call append_line(buffer, &
                "! Generator revision: "//chars(spec%generator_revision))
        end if
        call append_line(buffer, &
            "! Regenerate with: "//chars(spec%regenerate_command))
        call buffer%newline()
    end subroutine append_scalar_vector_banner

    subroutine append_scalar_vector_declarations(buffer, vector_size, tangent)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: vector_size
        logical, intent(in) :: tangent

        if (tangent) then
            call append_line(buffer, &
                "        real(c_double), intent(in) :: x, tangent")
        else
            call append_line(buffer, "        real(c_double), intent(in) :: x")
        end if
        call buffer%append("        real(c_double), intent(in) :: values(")
        call append_integer(buffer, vector_size)
        call buffer%append(")")
        call buffer%newline()
        if (tangent) then
            call buffer%append( &
                "        real(c_double), intent(in) :: dvalues(")
            call append_integer(buffer, vector_size)
            call buffer%append(")")
            call buffer%newline()
        end if
    end subroutine append_scalar_vector_declarations

    subroutine append_line(buffer, line)
        type(strbuf_t), intent(inout) :: buffer
        character(*), intent(in) :: line

        call buffer%append(line)
        call buffer%newline()
    end subroutine append_line

    function emit_enzyme_scalar_wrapper(spec) result(source)
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        type(str_t) :: source
        type(strbuf_t) :: buffer
        logical :: custom

        call validate_spec(spec)
        custom = len(chars(spec%custom_forward_symbol)) > 0
        call append_banner(buffer, spec)
        call append_module_header(buffer, spec, custom)
        call append_primal_interface(buffer, spec)
        call append_forward_interface(buffer, spec)
        call append_reverse_interface(buffer, spec)
        if (custom) call append_analytical_interface(buffer, spec)
        if (len(chars(spec%custom_forward_counter_symbol)) > 0) then
            call append_counter_interface(buffer, spec)
        end if
        call buffer%append("    end interface")
        call buffer%newline()
        call buffer%newline()
        call buffer%append("contains")
        call buffer%newline()
        call buffer%newline()
        call append_jvp(buffer, spec)
        call buffer%newline()
        call append_vjp(buffer, spec)
        if (spec%active_inputs == 1) then
            call buffer%newline()
            call append_scalar_vjp(buffer, spec)
        end if
        if (custom) then
            call buffer%newline()
            call append_custom_forward(buffer, spec)
        end if
        call buffer%newline()
        call buffer%append("end module ")
        call buffer%append(chars(spec%module_name))
        call buffer%newline()
        source = buffer%to_str()
    end function emit_enzyme_scalar_wrapper

    subroutine validate_spec(spec)
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        logical :: custom

        if (spec%active_inputs < 1 .or. spec%active_inputs > 5) then
            error stop "Enzyme scalar wrappers support one to five active inputs"
        end if
        if (len(chars(spec%module_name)) == 0) then
            error stop "Enzyme scalar wrapper module_name is required"
        end if
        if (len(chars(spec%wrapper_prefix)) == 0) then
            error stop "Enzyme scalar wrapper_prefix is required"
        end if
        if (len(chars(spec%primal_symbol)) == 0) then
            error stop "Enzyme scalar wrapper primal_symbol is required"
        end if
        custom = len(chars(spec%custom_forward_symbol)) > 0
        if (custom .and. len(chars(spec%analytical_jvp_symbol)) == 0) then
            error stop "custom forward rule requires analytical_jvp_symbol"
        end if
        if (.not. custom .and. &
            len(chars(spec%custom_forward_counter_symbol)) > 0) then
            error stop "custom forward counter requires custom_forward_symbol"
        end if
    end subroutine validate_spec

    subroutine append_banner(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("! Generated by fortsym. Do not edit.")
        call buffer%newline()
        call buffer%append("! Generator: ")
        call buffer%append(chars(spec%generator))
        call buffer%newline()
        if (len(chars(spec%generator_revision)) > 0) then
            call buffer%append("! Generator revision: ")
            call buffer%append(chars(spec%generator_revision))
            call buffer%newline()
        end if
        call buffer%append("! Regenerate with: ")
        call buffer%append(chars(spec%regenerate_command))
        call buffer%newline()
        call buffer%newline()
    end subroutine append_banner

    subroutine append_module_header(buffer, spec, custom)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        logical, intent(in) :: custom

        call buffer%append("module ")
        call buffer%append(chars(spec%module_name))
        call buffer%newline()
        call buffer%append( &
            "    use, intrinsic :: iso_c_binding, only: c_double, c_funloc, c_funptr")
        call buffer%newline()
        call buffer%append("    implicit none")
        call buffer%newline()
        call buffer%append("    private")
        call buffer%newline()
        if (spec%active_inputs > 1) then
            call buffer%newline()
            call buffer%append("    type, bind(c) :: enzyme_gradient_t")
            call buffer%newline()
            call buffer%append("        real(c_double) :: values(")
            call append_integer(buffer, spec%active_inputs)
            call buffer%append(")")
            call buffer%newline()
            call buffer%append("    end type enzyme_gradient_t")
            call buffer%newline()
        end if
        if (custom) then
            call buffer%newline()
            call buffer%append("    type, bind(c) :: enzyme_pair_t")
            call buffer%newline()
            call buffer%append("        real(c_double) :: primal, tangent")
            call buffer%newline()
            call buffer%append("    end type enzyme_pair_t")
            call buffer%newline()
        end if
        call buffer%newline()
        call buffer%append("    public :: ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp, ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp")
        if (spec%active_inputs == 1) then
            call buffer%append(", ")
            call buffer%append(chars(spec%wrapper_prefix))
            call buffer%append("_vjp_scalar")
        end if
        if (custom) then
            call buffer%append(", ")
            call buffer%append(chars(spec%custom_forward_symbol))
        end if
        call buffer%newline()
        call buffer%newline()
        call buffer%append("    interface")
        call buffer%newline()
    end subroutine append_module_header

    subroutine append_primal_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function primal(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(value) bind(c, name=""")
        call buffer%append(chars(spec%primal_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("            import :: c_double")
        call buffer%newline()
        call append_real_declaration(buffer, 12, "value", .false.)
        call append_input_declaration(buffer, 12, spec%active_inputs, .false.)
        call buffer%append("        end function primal")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_primal_interface

    subroutine append_forward_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function enzyme_fwddiff(function_pointer, ")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative) &")
        call buffer%newline()
        call buffer%append("                bind(c, name=""__enzyme_fwddiff"")")
        call buffer%newline()
        call buffer%append("            import :: c_double, c_funptr")
        call buffer%newline()
        call buffer%append( &
            "            type(c_funptr), value :: function_pointer")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .true.)
        call append_real_declaration(buffer, 12, "derivative", .false.)
        call buffer%append("        end function enzyme_fwddiff")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_forward_interface

    subroutine append_reverse_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function enzyme_autodiff(function_pointer, ")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(gradient) &")
        call buffer%newline()
        call buffer%append("                bind(c, name=""__enzyme_autodiff"")")
        call buffer%newline()
        if (spec%active_inputs == 1) then
            call buffer%append("            import :: c_double, c_funptr")
        else
            call buffer%append( &
                "            import :: c_double, c_funptr, enzyme_gradient_t")
        end if
        call buffer%newline()
        call buffer%append( &
            "            type(c_funptr), value :: function_pointer")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .false.)
        if (spec%active_inputs == 1) then
            call append_real_declaration(buffer, 12, "gradient", .false.)
        else
            call buffer%append("            type(enzyme_gradient_t) :: gradient")
            call buffer%newline()
        end if
        call buffer%append("        end function enzyme_autodiff")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_reverse_interface

    subroutine append_analytical_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function analytical_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative) bind(c, name=""")
        call buffer%append(chars(spec%analytical_jvp_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("            import :: c_double")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .true.)
        call append_real_declaration(buffer, 12, "derivative", .false.)
        call buffer%append("        end function analytical_jvp")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_analytical_interface

    subroutine append_counter_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        subroutine record_custom_rule() bind(c, name=""")
        call buffer%append(chars(spec%custom_forward_counter_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("        end subroutine record_custom_rule")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_counter_interface

    subroutine append_jvp(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("    function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative)")
        call buffer%newline()
        call buffer%append( &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call buffer%newline()
        call buffer%append("        real(c_double) :: derivative")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .true.)
        call buffer%newline()
        call buffer%append("        derivative = enzyme_fwddiff(c_funloc(primal), ")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append("    end function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp")
        call buffer%newline()
    end subroutine append_jvp

    subroutine append_vjp(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        integer :: input

        call buffer%append("    subroutine ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(", cotangent, ")
        call append_output_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append( &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .false.)
        call buffer%append("        real(c_double), value :: cotangent")
        call buffer%newline()
        call append_output_declaration(buffer, 8, spec%active_inputs)
        if (spec%active_inputs == 1) then
            call buffer%append("        real(c_double) :: gradient")
        else
            call buffer%append("        type(enzyme_gradient_t) :: gradient")
        end if
        call buffer%newline()
        call buffer%newline()
        call buffer%append("        gradient = enzyme_autodiff(c_funloc(primal), ")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        do input = 1, spec%active_inputs
            call buffer%append("        cotangent")
            call append_integer(buffer, input)
            call buffer%append(" = cotangent*gradient")
            if (spec%active_inputs > 1) then
                call buffer%append("%values(")
                call append_integer(buffer, input)
                call buffer%append(")")
            end if
            call buffer%newline()
        end do
        call buffer%append("    end subroutine ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp")
        call buffer%newline()
    end subroutine append_vjp

    subroutine append_scalar_vjp(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("    function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp_scalar(x1, cotangent) result(cotangent1)")
        call buffer%newline()
        call buffer%append( &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call buffer%newline()
        call buffer%append("        real(c_double), value :: x1, cotangent")
        call buffer%newline()
        call buffer%append("        real(c_double) :: cotangent1")
        call buffer%newline()
        call buffer%newline()
        call buffer%append( &
            "        cotangent1 = cotangent*enzyme_autodiff(c_funloc(primal), x1)")
        call buffer%newline()
        call buffer%append("    end function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp_scalar")
        call buffer%newline()
    end subroutine append_scalar_vjp

    subroutine append_custom_forward(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("    function ")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%append("(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(pair) bind(c, name=""")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .true.)
        call buffer%append("        type(enzyme_pair_t) :: pair")
        call buffer%newline()
        call buffer%newline()
        call buffer%append("        pair%primal = primal(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append("        pair%tangent = analytical_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        if (len(chars(spec%custom_forward_counter_symbol)) > 0) then
            call buffer%append("        call record_custom_rule()")
            call buffer%newline()
        end if
        call buffer%append("    end function ")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%newline()
    end subroutine append_custom_forward

    subroutine append_input_declaration(buffer, indentation, count, tangents)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation, count
        logical, intent(in) :: tangents
        integer :: input

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double), value :: ")
        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
            if (tangents) then
                call buffer%append(", tangent")
                call append_integer(buffer, input)
            end if
        end do
        call buffer%newline()
    end subroutine append_input_declaration

    subroutine append_output_declaration(buffer, indentation, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation, count
        integer :: input

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double), intent(out) :: ")
        call append_output_arguments(buffer, count)
        call buffer%newline()
    end subroutine append_output_declaration

    subroutine append_real_declaration(buffer, indentation, name, value)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation
        character(*), intent(in) :: name
        logical, intent(in) :: value

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double)")
        if (value) call buffer%append(", value")
        call buffer%append(" :: ")
        call buffer%append(name)
        call buffer%newline()
    end subroutine append_real_declaration

    subroutine append_primal_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
        end do
    end subroutine append_primal_arguments

    subroutine append_interleaved_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
            call buffer%append(", tangent")
            call append_integer(buffer, input)
        end do
    end subroutine append_interleaved_arguments

    subroutine append_output_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("cotangent")
            call append_integer(buffer, input)
        end do
    end subroutine append_output_arguments

    subroutine append_spaces(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count

        call buffer%append(repeat(" ", count))
    end subroutine append_spaces

    subroutine append_integer(buffer, value)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: value
        character(16) :: text

        write (text, "(i0)") value
        call buffer%append(trim(text))
    end subroutine append_integer

end module fortsym_enzyme
