module fortsym_enzyme
    use fortsym_string, only: str_t, strbuf_t, chars
    implicit none
    private

    type, public :: enzyme_scalar_wrapper_spec_t
        type(str_t) :: module_name
        type(str_t) :: wrapper_prefix
        type(str_t) :: primal_symbol
        integer :: active_inputs = 1
        type(str_t) :: analytical_jvp_symbol
        type(str_t) :: custom_forward_symbol
        type(str_t) :: custom_forward_counter_symbol
        type(str_t) :: generator
        type(str_t) :: generator_revision
        type(str_t) :: regenerate_command
    end type enzyme_scalar_wrapper_spec_t

    public :: emit_enzyme_scalar_wrapper

contains

    function emit_enzyme_scalar_wrapper(spec) result(source)
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        type(str_t) :: source
        type(strbuf_t) :: buffer
        logical :: custom

        call validate_spec(spec)
        custom = len(chars(spec%custom_forward_symbol)) > 0
        call append_banner(buffer, spec)
        call append_module_header(buffer, spec, custom)
        call append_primal_interface(buffer, spec)
        call append_forward_interface(buffer, spec)
        call append_reverse_interface(buffer, spec)
        if (custom) call append_analytical_interface(buffer, spec)
        if (len(chars(spec%custom_forward_counter_symbol)) > 0) then
            call append_counter_interface(buffer, spec)
        end if
        call buffer%append("    end interface")
        call buffer%newline()
        call buffer%newline()
        call buffer%append("contains")
        call buffer%newline()
        call buffer%newline()
        call append_jvp(buffer, spec)
        call buffer%newline()
        call append_vjp(buffer, spec)
        if (custom) then
            call buffer%newline()
            call append_custom_forward(buffer, spec)
        end if
        call buffer%newline()
        call buffer%append("end module ")
        call buffer%append(chars(spec%module_name))
        call buffer%newline()
        source = buffer%to_str()
    end function emit_enzyme_scalar_wrapper

    subroutine validate_spec(spec)
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        logical :: custom

        if (spec%active_inputs < 1 .or. spec%active_inputs > 4) then
            error stop "Enzyme scalar wrappers support one to four active inputs"
        end if
        if (len(chars(spec%module_name)) == 0) then
            error stop "Enzyme scalar wrapper module_name is required"
        end if
        if (len(chars(spec%wrapper_prefix)) == 0) then
            error stop "Enzyme scalar wrapper_prefix is required"
        end if
        if (len(chars(spec%primal_symbol)) == 0) then
            error stop "Enzyme scalar wrapper primal_symbol is required"
        end if
        custom = len(chars(spec%custom_forward_symbol)) > 0
        if (custom .and. len(chars(spec%analytical_jvp_symbol)) == 0) then
            error stop "custom forward rule requires analytical_jvp_symbol"
        end if
        if (.not. custom .and. &
            len(chars(spec%custom_forward_counter_symbol)) > 0) then
            error stop "custom forward counter requires custom_forward_symbol"
        end if
    end subroutine validate_spec

    subroutine append_banner(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("! Generated by fortsym. Do not edit.")
        call buffer%newline()
        call buffer%append("! Generator: ")
        call buffer%append(chars(spec%generator))
        call buffer%newline()
        if (len(chars(spec%generator_revision)) > 0) then
            call buffer%append("! Generator revision: ")
            call buffer%append(chars(spec%generator_revision))
            call buffer%newline()
        end if
        call buffer%append("! Regenerate with: ")
        call buffer%append(chars(spec%regenerate_command))
        call buffer%newline()
        call buffer%newline()
    end subroutine append_banner

    subroutine append_module_header(buffer, spec, custom)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        logical, intent(in) :: custom

        call buffer%append("module ")
        call buffer%append(chars(spec%module_name))
        call buffer%newline()
        call buffer%append( &
            "    use, intrinsic :: iso_c_binding, only: c_double, c_funloc, c_funptr")
        call buffer%newline()
        call buffer%append("    implicit none")
        call buffer%newline()
        call buffer%append("    private")
        call buffer%newline()
        if (spec%active_inputs > 1) then
            call buffer%newline()
            call buffer%append("    type, bind(c) :: enzyme_gradient_t")
            call buffer%newline()
            call buffer%append("        real(c_double) :: values(")
            call append_integer(buffer, spec%active_inputs)
            call buffer%append(")")
            call buffer%newline()
            call buffer%append("    end type enzyme_gradient_t")
            call buffer%newline()
        end if
        if (custom) then
            call buffer%newline()
            call buffer%append("    type, bind(c) :: enzyme_pair_t")
            call buffer%newline()
            call buffer%append("        real(c_double) :: primal, tangent")
            call buffer%newline()
            call buffer%append("    end type enzyme_pair_t")
            call buffer%newline()
        end if
        call buffer%newline()
        call buffer%append("    public :: ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp, ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp")
        if (custom) then
            call buffer%append(", ")
            call buffer%append(chars(spec%custom_forward_symbol))
        end if
        call buffer%newline()
        call buffer%newline()
        call buffer%append("    interface")
        call buffer%newline()
    end subroutine append_module_header

    subroutine append_primal_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function primal(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(value) bind(c, name=""")
        call buffer%append(chars(spec%primal_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("            import :: c_double")
        call buffer%newline()
        call append_real_declaration(buffer, 12, "value", .false.)
        call append_input_declaration(buffer, 12, spec%active_inputs, .false.)
        call buffer%append("        end function primal")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_primal_interface

    subroutine append_forward_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function enzyme_fwddiff(function_pointer, ")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative) &")
        call buffer%newline()
        call buffer%append("                bind(c, name=""__enzyme_fwddiff"")")
        call buffer%newline()
        call buffer%append("            import :: c_double, c_funptr")
        call buffer%newline()
        call buffer%append( &
            "            type(c_funptr), value :: function_pointer")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .true.)
        call append_real_declaration(buffer, 12, "derivative", .false.)
        call buffer%append("        end function enzyme_fwddiff")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_forward_interface

    subroutine append_reverse_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function enzyme_autodiff(function_pointer, ")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(gradient) &")
        call buffer%newline()
        call buffer%append("                bind(c, name=""__enzyme_autodiff"")")
        call buffer%newline()
        if (spec%active_inputs == 1) then
            call buffer%append("            import :: c_double, c_funptr")
        else
            call buffer%append( &
                "            import :: c_double, c_funptr, enzyme_gradient_t")
        end if
        call buffer%newline()
        call buffer%append( &
            "            type(c_funptr), value :: function_pointer")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .false.)
        if (spec%active_inputs == 1) then
            call append_real_declaration(buffer, 12, "gradient", .false.)
        else
            call buffer%append("            type(enzyme_gradient_t) :: gradient")
            call buffer%newline()
        end if
        call buffer%append("        end function enzyme_autodiff")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_reverse_interface

    subroutine append_analytical_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        function analytical_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative) bind(c, name=""")
        call buffer%append(chars(spec%analytical_jvp_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("            import :: c_double")
        call buffer%newline()
        call append_input_declaration(buffer, 12, spec%active_inputs, .true.)
        call append_real_declaration(buffer, 12, "derivative", .false.)
        call buffer%append("        end function analytical_jvp")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_analytical_interface

    subroutine append_counter_interface(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("        subroutine record_custom_rule() bind(c, name=""")
        call buffer%append(chars(spec%custom_forward_counter_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call buffer%append("        end subroutine record_custom_rule")
        call buffer%newline()
        call buffer%newline()
    end subroutine append_counter_interface

    subroutine append_jvp(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("    function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(derivative)")
        call buffer%newline()
        call buffer%append( &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call buffer%newline()
        call buffer%append("        real(c_double) :: derivative")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .true.)
        call buffer%newline()
        call buffer%append("        derivative = enzyme_fwddiff(c_funloc(primal), ")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append("    end function ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_jvp")
        call buffer%newline()
    end subroutine append_jvp

    subroutine append_vjp(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec
        integer :: input

        call buffer%append("    subroutine ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(", cotangent, ")
        call append_output_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append( &
            "        use, intrinsic :: iso_c_binding, only: c_double, c_funloc")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .false.)
        call buffer%append("        real(c_double), value :: cotangent")
        call buffer%newline()
        call append_output_declaration(buffer, 8, spec%active_inputs)
        if (spec%active_inputs == 1) then
            call buffer%append("        real(c_double) :: gradient")
        else
            call buffer%append("        type(enzyme_gradient_t) :: gradient")
        end if
        call buffer%newline()
        call buffer%newline()
        call buffer%append("        gradient = enzyme_autodiff(c_funloc(primal), ")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        do input = 1, spec%active_inputs
            call buffer%append("        cotangent")
            call append_integer(buffer, input)
            call buffer%append(" = cotangent*gradient")
            if (spec%active_inputs > 1) then
                call buffer%append("%values(")
                call append_integer(buffer, input)
                call buffer%append(")")
            end if
            call buffer%newline()
        end do
        call buffer%append("    end subroutine ")
        call buffer%append(chars(spec%wrapper_prefix))
        call buffer%append("_vjp")
        call buffer%newline()
    end subroutine append_vjp

    subroutine append_custom_forward(buffer, spec)
        type(strbuf_t), intent(inout) :: buffer
        type(enzyme_scalar_wrapper_spec_t), intent(in) :: spec

        call buffer%append("    function ")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%append("(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(") result(pair) bind(c, name=""")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%append(""")")
        call buffer%newline()
        call append_input_declaration(buffer, 8, spec%active_inputs, .true.)
        call buffer%append("        type(enzyme_pair_t) :: pair")
        call buffer%newline()
        call buffer%newline()
        call buffer%append("        pair%primal = primal(")
        call append_primal_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        call buffer%append("        pair%tangent = analytical_jvp(")
        call append_interleaved_arguments(buffer, spec%active_inputs)
        call buffer%append(")")
        call buffer%newline()
        if (len(chars(spec%custom_forward_counter_symbol)) > 0) then
            call buffer%append("        call record_custom_rule()")
            call buffer%newline()
        end if
        call buffer%append("    end function ")
        call buffer%append(chars(spec%custom_forward_symbol))
        call buffer%newline()
    end subroutine append_custom_forward

    subroutine append_input_declaration(buffer, indentation, count, tangents)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation, count
        logical, intent(in) :: tangents
        integer :: input

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double), value :: ")
        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
            if (tangents) then
                call buffer%append(", tangent")
                call append_integer(buffer, input)
            end if
        end do
        call buffer%newline()
    end subroutine append_input_declaration

    subroutine append_output_declaration(buffer, indentation, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation, count
        integer :: input

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double), intent(out) :: ")
        call append_output_arguments(buffer, count)
        call buffer%newline()
    end subroutine append_output_declaration

    subroutine append_real_declaration(buffer, indentation, name, value)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: indentation
        character(*), intent(in) :: name
        logical, intent(in) :: value

        call append_spaces(buffer, indentation)
        call buffer%append("real(c_double)")
        if (value) call buffer%append(", value")
        call buffer%append(" :: ")
        call buffer%append(name)
        call buffer%newline()
    end subroutine append_real_declaration

    subroutine append_primal_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
        end do
    end subroutine append_primal_arguments

    subroutine append_interleaved_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("x")
            call append_integer(buffer, input)
            call buffer%append(", tangent")
            call append_integer(buffer, input)
        end do
    end subroutine append_interleaved_arguments

    subroutine append_output_arguments(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count
        integer :: input

        do input = 1, count
            if (input > 1) call buffer%append(", ")
            call buffer%append("cotangent")
            call append_integer(buffer, input)
        end do
    end subroutine append_output_arguments

    subroutine append_spaces(buffer, count)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: count

        call buffer%append(repeat(" ", count))
    end subroutine append_spaces

    subroutine append_integer(buffer, value)
        type(strbuf_t), intent(inout) :: buffer
        integer, intent(in) :: value
        character(16) :: text

        write (text, "(i0)") value
        call buffer%append(trim(text))
    end subroutine append_integer

end module fortsym_enzyme
